### PR TITLE
feat: change incoming payment `state: enum` into `completed: boolean`

### LINKED ISSUE #104: Open Payment Spec update: * remove `state` in incoming and outgoing payments
* incoming payment: 
  * add `completed` flag
  * payment is expired if `completed=false` and `now>expiresAt`
  * if payment is not complete and not expired, it is `pending`
* outgoing payment: 
  * add `failed` flag
  * payment is complete if `sendAmount=sentAmount`
  * if payment has not failed and `sendAmount!=sentAmount`, payment is `pending`
 
@wilsonianb lmk if I summarized that correctly

### PR DESCRIPTION
**Pull request by sabineschaller**
fixes #104

### CODE REVIEW

**Comment by wilsonianb** [comment]
I'm being obstinate:
https://github.com/interledger/open-payments/issues/104#issuecomment-1118660065

Also this should either also include changes to outgoing payment state from #104 or not use the `fixes` keyword to auto-close the issue. (Or #104 could be separated into multiple issues)

**Comment by sabineschaller** [comment]
> I'm being obstinate:
https://github.com/interledger/open-payments/issues/104#issuecomment-1118660065

:eyes: 

> Also this should either also include changes to outgoing payment state from https://github.com/interledger/open-payments/issues/104 or not use the fixes keyword to auto-close the issue. (Or https://github.com/interledger/open-payments/issues/104 could be separated into multiple issues)

I was under the impression that you have already included the changes for outgoing payments in a previous PR and that this one would complete the issue.

**Comment by wilsonianb** [comment]
:upside_down_face: oops, you're right.
https://github.com/interledger/open-payments/pull/97/commits/9a91081daf5250e49075a4e226e2afdd2b7611f8

**Comment by sabineschaller** [comment]
Newer version: https://github.com/interledger/open-payments/pull/126

**Pull request closed without merging**
